### ISSUE TITLE
Improve memory when uploading large file

### ISSUE THREAD

**Issue by kurpitsa** [mschilli/net-google-drive-simple#11]
When uploading big files, the module tends to get stuck in computer without too much memory (like mine). In file_upload, instead of

```perl
my $req = &HTTP::Request::Common::PUT(
    $url->as_string,
    $self->{ oauth }->authorization_headers(),
    "Content-Type" => $mime_type,
    Content        => $file_data,
);  
```

I think that giving the reference of file_data instead:

```perl
my $req = &HTTP::Request::Common::PUT(
    $url->as_string,
    $self->{ oauth }->authorization_headers(),
    "Content-Type" => $mime_type,
    Content        => \$file_data,
);  
```

might alleviate the problem (after this change I managed to upload rather big files). Please reject this if I am wrong, I do not know the internals of HTTP::Message very well.

**Comment by atoomic** [comment]
Hi @kurpitsa you are indeed wrong, storing a reference, will not reduce the memory used.
The reference points to the whole string (SvPV). One way to reduce it would be to use a file handle and read it as we write the output.

I think we can keep this case open in order to try to improve memory for uploading large files

**Comment by troglodyne** [comment]
Interestingly, the version cPanel ships has a patch to "sip" memory via use of a subroutine passed in as `Content`.

Unfortunately on the latest version of LWP, this approach breaks (as passing in subroutines for content now only works when not using the helper libraries directly (instead we need to be using HTTP::Request->new() as the documentation for that package suggests).

Guess I may as well submit that bit as well, as otherwise the patch I make to "fix" that isn't even necessary without the patch from cPanel to enable using a subroutine as Content for file uploads.

**Comment by troglodyne** [comment]
Got the updates passing all but one of the assertions when running the "live" test
```
LIVE_TEST=1 PERL5LIB=lib/ prove -mv t/001Basic.t
```
Gotta take care of some stuff this afternoon, so will probably finish that bit up in the morning then submit the PR
